{
  "version": 1,
  "Resources": [
    {
      "TargetService": {
        "Type": "AWS::ECS::Service",
        "Properties": {
          "TaskDefinition": "arn:aws:ecs:eu-west-2:938694781525:task-definition/sample-website:5",
          "LoadBalancerInfo": {
            "ContainerName": "sample-website",
            "ContainerPort": 5000
          }
        }
      }
    }
  ]
}
